### ISSUE TITLE
Problems with UTF-8 delimiter splitting.

### ISSUE THREAD

**Issue by nbeitner** [MarkPflug/Sylvan#67] opened 2021-07-18 22:09 UTC
I was trying Sylvan csv and I was really struggling with using it until I found that there is a peculiar anomaly.

iIncome_Source_Sub_Source_Mapping_ID,iIncome_Source_ID,sIncome_Sub_Source,sIncome_Sub_Source_2,iIncome_Sub_Source_ID,blnActive
567774,11014,(주)다올소프트,기타녹음,NULL,1
394394,11014,(주)달콤소프트,유선전송,NULL,1
601057,11014,(주)대교,기타녹음,NULL,1

The first row should have NULL at GetValue(5) … it seems to be splitting in the Unicode field, returning (주)다 as a column instead of (주)다올소프트 and 소프트 for the next column … and splitting on 올.

What is interesting, is if I remove the last two rows in the CSV, it works and does not exhibit this behavior …

using var s = File.OpenRead("Income_Source_Sub_Source_Mapping.csv");
using var reader = new StreamReader(s, Encoding.UTF8);
var options = new CsvDataReaderOptions()
{
       HasHeaders = true,
       Delimiter = ','
};

using var csv = CsvDataReader.GetReader(s);

while (csv.Read())
{
       if ((string)csv.GetValue(0) == "567774")
       {
              var x = csv.GetValue(5);

              Debug.Assert(x == "1");
       }

}

What I am curious about is, why should following data affect how a previous row is decoded?

Does this reader process row by row, or the whole stream first?

[Income_Source_Sub_Source_Mapping.zip](https://github.com/MarkPflug/Sylvan/files/6837016/Income_Source_Sub_Source_Mapping.zip)

**Comment by MarkPflug** [comment] 2021-07-18 22:45
What version of the library are you using?

**Comment by nbeitner** [comment] 2021-07-18 23:10
1.1.1 from NuGet latest.

**Comment by MarkPflug** [comment] 2021-07-19 00:12
Thanks for the bug report! This was a regression I introduced in 1.1.0 in some SIMD logic that I added. I just pushed a fix in 1.1.2. Might take a few minutes for nuget to list it.

https://github.com/MarkPflug/Sylvan/blob/0d92d94846a00947177dd821a58e2b00ad24f8c7/source/Sylvan.Data.Csv.Tests/CsvDataReaderTests.cs#L1231

**Closed by MarkPflug** 2021-07-19 00:12 UTC

**Comment by nbeitner** [comment] 2021-07-21 17:36
Out of interest, why does

public long Write(DbDataReader reader)

Require a DbDataReader?

Why don’t you use IDataReader?

Then you can support a much wider range of data sources.

I have an IDataReader that I wanted to save to csv, and I can’t because you require a much more complex contract, for which there seems to be no reason.

Any chance you can change the contract to support the IDataReader

**Comment by MarkPflug** [comment] 2021-07-21 17:53
Where is your IDataReader coming from? The vast majority of modern ado data providers expose readers that derive from DbDataReader.

To answer your question, one reason why I use DbDataReader is because it exposes async apis. The library is designed to support fully async IO, which simply isn't possible with IDataReader. Of course, you're using the sync `Write` API, so this probably isn't a concern to you.

I have another library that can help you here `Sylvan.Data`. It exposes an extension method  `IDataReader.AsDbDataReader`, which will adapt (or cast) an IDataReader to a DbDataReader. This includes exposing an implementation of `IDbColumnSchemaGenerator.GetColumnSchema` which is a modern, easier to use replacement for `IDataReader.GetSchemaTable`. The `CsvDataWriter` uses this schema information to efficiently process and serialize the data. The Sylvan.Data package is currently pre-release and some things in there are likely to change before it gets to 1.0. However, you can count on the `AsDbDataReader` continuing to work without modification. Or, you know, you could just copy the relevant code into your own project if you needed, is isn't much code, and it isn't very complex.

**Comment by nbeitner** [comment] 2021-07-21 18:04
I have written a bunch of classes that implement IDataReader ... I will look into whether I can derive them from DbDataReader ...

**Comment by MarkPflug** [comment] 2021-07-21 18:23
Let me know if you run into any issues. I'll be curious to see if your data reader implementations satisfy the demands of my library. Are your IDataReaders typed, meaning do they support more than GetString? And if so, do they implement GetFieldType? Can you interrogate the schema: access `FieldCount`, `GetFieldType`, and `GetSchemaTable` before calling Read for the first time? Do you provide an implementation of GetSchemaTable or just throw NotSupportedException? It last one isn't required, I'm just curious if you do implement it, because many community implementations I've seen don't.

**Comment by nbeitner** [comment] 2021-07-21 19:01
I implement pretty much all of the interfaces, though I tend to use GetValue() most of the time.
I make extensive use of GetSchemaTable()
I have a toolkit of Linq like functions which work on IDataReader rather than IEnumerable<T>.
I am having a philosophical dilemma about using IDataReaders rather than strongly typed interfaces for dynamic objects.
The main reason is object transformation and augmentation in a pipeline where any stage may only know part of the data contract.
I'd be happy to discuss it further with you in a different medium.
