### ISSUE TITLE
Truncated output of CsvDataWriter

### ISSUE THREAD

**Issue by martinsuchan** [MarkPflug/Sylvan#146] opened 2022-08-18 17:43 UTC
When I was creating small app for converting large datasets from one CSV format to another, in sizes about 10 millions lines on the input and 500K rows on the output, I noticed that the CSV output created by CsvDataWriter was always, deterministically(!), truncated by about 100-1000 characters. Simply set each file was missing from half a line to about few lines.

I tried using proper usings and await syntax with the CsvDataWriter, tried to find any "Flush" API I might have missed, but the output was always the same, always trimmed on the same position.

Please check the CsvDataWriter implementation, it looks like it's not counting the required buffer properly and truncating the output sooner with the result of data corruption.

**Comment by MarkPflug** [comment] 2022-08-18 17:48
This is almost certainly due to not flushing/closing one of the streams properly. Show me some code the reproduces the issue.

**Comment by martinsuchan** [comment] 2022-08-18 17:49
Method I used for the serialization:

async Task WriteCsvToFile(string outPath, object[] o)
{
  await using DbDataReader recordREader = o.AsDataReader();
  var csvWriter = CsvDataWriter.Create(outPath);
  await csvWriter.WriteAsync(recordReader);
}

The record structure I serialized had only two columns, one stringId, second string with object serialized as json, so the CsvDataWriter had to do lots of escapings.

**Comment by MarkPflug** [comment] 2022-08-18 17:54
This code doesn't compile. object[].AsDataReader() wouldn't write any records either, because the type  (T) would be object, which has no properties. So, I'm guessing your real code is more complicated than this example.

**Comment by martinsuchan** [comment] 2022-08-18 17:58
It compiles, targeting .net 6.0 the project uses Sylvan.Data.Csv 1.1.16 and Sylvan.Data 0.2.3.
I'm using the method for serializing array of anonymous types.

**Comment by MarkPflug** [comment] 2022-08-18 18:00
>It compiles

"recordREader" vs "recordReader"
I don't believe you.

**Comment by martinsuchan** [comment] 2022-08-18 18:01
Ok, fixed the typo :)

**Comment by MarkPflug** [comment] 2022-08-18 18:08
Try changing:
`var csvWriter = CsvDataWriter.Create(outPath);`
to
`using var csvWriter = CsvDataWriter.Create(outPath);`

**Comment by martinsuchan** [comment] 2022-08-18 18:26
So update, you're right, that with that parameter object[] it serializes empty lines. Originally I had the serialization logic outside that method.
Also after changing it to `using var csvWriter = CsvDataWriter.Create(outPath);` it works 🎉
I'm testing in on my second laptop with real data that I cannot share here.

So it looks like it works when using the API properly, the only question is why there is no warning in VS that I should be using `await using` with that type? Usually VS is quite vocal when I miss using for a disposable type somewhere.

**Comment by MarkPflug** [comment] 2022-08-18 18:40
> why there is no warning in VS

That's a good question, and I thought that the code analysis packages would provide this now, but apparently not.

If you want to have a helper method like this, it needs a generic type parameter (`T`) to allow the AsDataReader to discover the properties:
```C#
async Task WriteAsync<T>(string filename, IEnumerable<T> data) where T : class
{
    using var r = data.AsDataReader();
    await using var w = CsvDataWriter.Create(filename);
    await w.WriteAsync(r);
}
```

Glad to hear your problem is solved. If you find these libraries useful, please give the repository a star.

**Closed by MarkPflug** 2022-08-18 18:40 UTC
